apiVersion: v1
description: A Helm chart for using Matomo
name: matomo
version: 0.0.1
appVersion: 0.0.1
home: https://matomo.org
icon: "https://bitnami.com/assets/stacks/matomo/img/matomo-stack-110x117.png"
sources:
- https://github.com/statcan/StatCan.OrchardCore
maintainers:
- name: jptissot
  email: jean-philippe.tissot@canada.ca
