apiVersion: v2
type: application
description: An extended Helm chart derived from official Velero chart.
name: velero
version: 0.2.0
appVersion: 1.3.2
home: https://heptio.com/products/#heptio-velero
sources:
- https://github.com/heptio/velero
maintainers:
- name: sylus
  email: william.hearn@canada.ca
- name: zachomedia
  email: zachary.seguin@canada.ca
engine: gotpl
dependencies:
- name: velero
  version: 2.9.15
  repository: https://vmware-tanzu.github.io/helm-charts
