{{- if .Values.nsiReset.enabled -}}
{{- if .Values.nsiReset.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dotstatsuite.nsiReset.serviceAccountName" . }}-reset
  labels:
    {{- include "dotstatsuite.labels" . | nindent 4 }}-reset
  {{- with .Values.nsiReset.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end -}}
