{{- if .Values.nsiStaging.enabled -}}
{{- if .Values.nsiStaging.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dotstatsuite.nsiStaging.serviceAccountName" . }}-staging
  labels:
    {{- include "dotstatsuite.labels" . | nindent 4 }}-staging
  {{- with .Values.nsiStaging.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end -}}
