{{- if .Values.vault.destinationRule.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ template "vault.fullname" . }}
  labels:
    helm.sh/chart: {{ include "vault.chart" . }}
    app.kubernetes.io/name: {{ include "vault.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.Version | quote }}
spec:
  host: "{{ template "vault.fullname" . }}.{{ .Release.Namespace }}.svc.{{ default "cluster.local" .Values.vault.clusterDomain }}"
  trafficPolicy:
    tls:
      mode: "{{ default "DISABLE" .Values.vault.destinationRule.mode }}"
{{- end }}
