apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "geoserver.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "geoserver.name" . }}
    helm.sh/chart: {{ include "geoserver.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  geowebcache-diskquota-jdbc.xml: |
{{ tpl (.Files.Get "conf/geowebcache-diskquota-jdbc.xml") . | indent 4 }}
  geowebcache-diskquota.xml: |
{{ tpl (.Files.Get "conf/geowebcache-diskquota.xml") . | indent 4 }}
