apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "profiles-controller.fullname" . }}
  labels:
    {{- include "profiles-controller.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "profiles-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorizatio.k8s.io
  kind: ClusterRole
  name: {{ include "controller.fullname" . }}
