apiVersion: v1
description: A Helm chart that hosts OrchardCore with PostgreSql
name: orchard-cms
version: 1.1.0
appVersion: 1.0.0
home: https://www.orchardcore.net/
sources:
- https://github.com/statcan/StatCan.OrchardCore
maintainers:
- name: jptissot
  email: jean-philippe.tissot@canada.ca
dependencies:
  - name: postgresql
    version: 9.8.4
    repository: https://charts.bitnami.com/bitnami
