#fluetd-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-configmap
  labels:
    app: fluentd
    kubernetes.io/cluster-service: "true"
data:
  fluent.conf: |
    <source>
      @type null
    </source>
    <match **>
        @type elasticsearch
        include_timestamp true
        index_name "vetting-reqs-dev"
        hosts "https://{{ .Values.configmodulePy.elasticSearchUrl }}"
        user "{{ .Values.configmodulePy.elasticSearchUsername }}"
        password "{{ .Values.configmodulePy.elasticSearchPassword }}"

    </match>