#fluetd-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-configmap
  labels:
    app: fluentd
    kubernetes.io/cluster-service: "true"
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
    </source>
    <match **>
        @type elasticsearch
        include_tag_key true
        logstash_format true
        logstash_prefix logstash
        host "{{ .Values.configmodulePy.elasticSearchUrl }}"
        port "443"
        scheme "https"
        user "{{ .Values.configmodulePy.elasticSearchUsername }}"
        password "{{ .Values.configmodulePy.elasticSearchPassword }}"
        reload_connections false
        reconnect_on_error true
    </match>