#fluetd-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-configmap
  labels:
    app: fluentd
    kubernetes.io/cluster-service: "true"
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      tag kubernetes.*
      read_from_head true
      <parse>
        @type json
        time_format %Y-%m-%dT%H:%M:%S.%NZ
      </parse>      
    </source>
    <match **>
        @type elasticsearch
        include_timestamp true
        logstash_format true
        host {{ .Values.configmodulePy.elasticSearchUrl }}
        port 9200
        user {{ .Values.configmodulePy.elasticSearchUsername }}
        password {{ .Values.configmodulePy.elasticSearchPassword }}

    </match>