#fluetd-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  labels:
    app: fluentd
    kubernetes.io/cluster-service: "true"
data:
  fluent.conf: |
    <source>
      @type mounted-file
      path /app/logs/requests.log
    </source>
    <match **>
        @type elasticsearch
        include_timestamp true
        logstash_format true
        host {{ .Values.configmodulePy.elasticSearchUrl }}
        port 443
        user {{ .Values.configmodulePy.elasticSearchUsername }}
        password {{ .Values.configmodulePy.elasticSearchPassword }}
    </match>