apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: report-timeVetting-monthly-vetting-job
spec:
  schedule: "*/1 * * * *"
  #schedule: "0 0 1 * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: report-timeVetting-monthly-vetting-job
            image: "{{ .Values.appImageReportCron.repository }}:{{ .Values.appImageReportCron.tag }}"
            imagePullPolicy: "{{ .Values.appImageReportCron.pullPolicy }}"
            args: ["time_spent_vetting","monthly"]
            env:
            - name: STORAGE_ACCOUNT_NAME
              valueFrom:
                secretKeyRef:
                  name: reports-cronjob-init
                  key: storageAccountName
            - name: STORAGE_ACCOUNT_RESOURCE_GROUP
              valueFrom:
                secretKeyRef:
                  name: reports-cronjob-init
                  key: storageAccountResourceGroup
            - name: DB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: db-cronjob-init
                  key: dbConnectionString
            volumeMounts:
              - name: {{ include "vetting-app.fullname" . }}-{{ .Values.entrypointSh.name }}
                mountPath: {{ .Values.entrypointSh.mountPath }}
                subPath: {{ .Values.entrypointSh.subPath }}
          volumes:
            - name:  {{ include "vetting-app.fullname" . }}-{{ .Values.entrypointSh.name }}
              secret:
                secretName: {{ include "vetting-app.fullname" . }}-reports-cronjob-{{ .Values.entrypointSh.name }}-reports-secret
                defaultMode: 0755         
          restartPolicy: OnFailure
         
