apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vetting-app.fullname" . }}-{{ .Values.configmodulePy.name }}-secret
  labels:
    app.kubernetes.io/name: {{ include "vetting-app.fullname" . }}
    helm.sh/chart: {{ include "vetting-app.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    
type: Opaque
stringData:
  configmodule.py: |-
    class Config:
      SQLALCHEMY_DATABASE_URI = "postgresql://{{ .Values.postgresql.postgresqlUsername }}:{{ .Values.postgresql.postgresqlPassword }}@vetting-postgresql:5432/{{ .Values.postgresql.postgresqlDatabase }}"
      SQLALCHEMY_TRACK_MODIFICATIONS = "False"
      SECRET_KEY = "{{ .Values.configmodulePy.secretKey }}"
    
      SESSION_TYPE="sqlalchemy"
      PERMANENT_SESSION_LIFETIME=1200
      SESSION_USE_SIGNER=True
      SESSION_SQLALCHEMY_TABLE="Sessions"
    
      EMAIL_ENABLE_NOTIFICATIONS={{ .Values.configmodulePy.emailEnableNotifications }}
      EMAIL_STMP_SERVER="email-smtp.ca-central-1.amazonaws.com"
      EMAIL_USERNAME="{{ .Values.configmodulePy.emailUsername }}" #need to be encrypted or store in key vault
      EMAIL_PASSWORD="{{ .Values.configmodulePy.emailPassword }}" #need to be encrypted or stored in key vault
      EMAIL_SENDER_EMAIL="statcan.donotreply-nepasrepondre.statcan@statcan.gc.ca"
      EMAIL_RECEIVER_EMAIL="{{ .Values.configmodulePy.emailReceiverEmail }}" #statcan.virtualdatalab-laboratoiredesdonneesvirtuel.statcan@canada.ca"
      EMAIL_PORT=25
    
      CLIENT_SECRET = "{{ .Values.configmodulePy.clientSecret }}" # Our Quickstart uses this placeholder
    
      CLIENT_ID = "{{ .Values.configmodulePy.clientID }}"
      
      STORAGE_ANALYST_NAME = "{{ .Values.configmodulePy.storageAnalystName }}"
      STORAGE_RESEARCHER_NAME = "{{ .Values.configmodulePy.storageResearcherName }}"

      AUTHORITY = "https://login.microsoftonline.com/{{ .Values.configmodulePy.tenantID }}"  # For multi-tenant app
      LOGOUT="https://login.microsoftonline.com/{{ .Values.configmodulePy.tenantID }}/oauth2/v2.0/logout"
    
      ENDPOINT = 'https://graph.microsoft.com/v1.0/users'  # This resource requires no admin consent
      SCOPE = ["User.ReadBasic.All"]
      APP_RELEASE_DATE="{{ .Values.configmodulePy.appReleaseDate }}"
      APP_RELEASE_VERSION="{{ .Values.configmodulePy.appReleaseVersion }}"
    
    class ProductionConfig(Config):
      SQLALCHEMY_DATABASE_URI = "postgresql://testuser:testpassword@vetting-postgresql:5432/DisclosureVettingDb"
