apiVersion: v1
kind: Secret
metadata:
  name: db-cronjob-init
type: Opaque
stringData:
  dbConnectionString: postgresql://{{ .Values.external.postgresqlUsername }}:{{ .Values.external.postgresqlPassword }}@{{ .Values.external.host }}:{{ .Values.external.port }}/{{ .Values.external.postgresqlDatabase }}
  researcherAccounts: insertData
  analystAccounts: insertData
  adminAccounts: insertData
  projectsData: insertData
