apiVersion: v1
kind: Secret
metadata:
  name: db-cronjob-init
type: Opaque
stringData:
  dbConnectionString: postgresql://user:password@host:port/db
  researcherAccounts: insertData
  analystAccounts: insertData
  adminAccounts: insertData
  projectsData: insertData
