apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vetting-app.fullname" . }}-AD-scan-cronjob-{{ .Values.entrypointSh.name }}-secret
type: Opaque
stringData:
  entrypoint.sh: |-
        #!/bin/bash
        set -e
{{- if .Values.external.enabled }}
        while ! nc -z {{ .Values.external.host }} {{ .Values.external.port }}; do
{{- else if .Values.postgresql.enabled }}
        while ! nc -z {{ .Release.Name }}-postgresql 5432; do
{{- end }}

          echo "Waiting for POSTGRES!"
          sleep 0.1
        done

        echo "Scan for new users and projects"
        flask users scan_for_users

        gunicorn --bind 0.0.0.0:5000 --workers 4 --threads 50 run:app
