apiVersion: v1
kind: Secret
metadata:
  name: reports-cronjob-init
type: Opaque
stringData:
  dbConnectionString: postgresql://{{ .Values.external.postgresqlUsername }}:{{ .Values.external.postgresqlPassword }}@{{ .Values.external.host }}:{{ .Values.external.port }}/{{ .Values.external.postgresqlDatabase }}
  storageAccountName: {{ .Values.reportsCronJob.storageAccountName }}
  storageAccountResourceGroup: {{ .Values.reportsCronJob.storageAccountResourceGroup }}
  storageAccountFileShareName: {{ .Values.reportsCronJob.storageAccountFileShareName }}
  elasticSearchUrl: {{ .Values.configmodulePy.elasticSearchUrl }}
  elasticSearchUsername: {{ .Values.configmodulePy.elasticSearchUsername }}
  elasticSearchPassword: {{ .Values.configmodulePy.elasticSearchPassword }}
  elasticSearchLogsIndex: {{ .Values.reportsCronJob.elasticSearchLogsIndex }}
  elasticSearchErrorsIndex: {{ .Values.reportsCronJob.elasticSearchErrorsIndex }}