apiVersion: v1
kind: Secret
metadata:
  name: reports-cronjob-init
type: Opaque
stringData:
  storageAccountName: {{ .Values.reportsCronJob.storageAccountName }}
  storageResourceGroupName: {{ .Values.reportsCronJob.storageResourceGroup }}
