dependencies:
  - name: postgresql
    version: 7.0.1
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 10.5.6
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
