apiVersion: v1
kind: Secret
metadata:
  name: cronjob-secret
type: Opaque
stringData:
  elasticUrl: "{{ .Values.appConfig.elasticUrl }}"
  elasticPassword: "{{ .Values.appConfig.elasticPassword }}"
  elasticUsername: "{{ .Values.appConfig.elasticUsername }}"
  elasticErrorIndex: "{{ .Values.appConfig.elasticErrorIndex }}"
  apiUrl: {{ .Values.appConfig.apiUrl }}
  storageAccountName: {{ .Values.appConfig.storageAccountName }}
  storageAccountResourceGroupName: {{ .Values.appConfig.storageAccountResourceGroupName }}
  storageContainerName: {{ .Values.appConfig.storageContainerName }}