apiVersion: v1
kind: Service
metadata:
  name: {{ include "analytics-platform.fullname" . }}-portal
  labels:
    app.kubernetes.io/name: {{ include "analytics-platform.name" . }}
    helm.sh/chart: {{ include "analytics-platform.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.portal.service.type }}
  ports:
    - port: {{ .Values.portal.service.port }}
      targetPort: 8000
      protocol: TCP
      name: portal
  selector:
    app.kubernetes.io/name: {{ include "analytics-platform.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: portal
