kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.fullnameOverride }}-db-secret
data:
{{- if index .Values "mssql-linux" "enabled" }}
  sapassword: {{ index .Values "mssql-linux" "sapassword" | b64enc }}
{{- else }}
  sapassword: {{ .Values.managed.database.sapassword | b64enc }}
{{- end }}
type: Opaque
