{{- if .Values.nsiDesign.enabled -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.fullnameOverride }}-mssql-sdmx-design-data
data:
  password: {{ .Values.managed.database.password | b64enc }}
type: Opaque
{{- end -}}
