apiVersion: v1
kind: Secret
metadata:
  name: {{ include "analytics-platform.fullname" . }}-elasticsearch
  labels:
    app.kubernetes.io/name: {{ include "analytics-platform.name" . }}
    helm.sh/chart: {{ include "analytics-platform.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  uri: {{ .Values.elasticsearch.uri | b64enc | quote }}