apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "varnish.fullname" . }}"
  labels:
{{ include "varnish.labels" . | indent 4 }}
data:
{{- if .Values.varnishConfigContent }}
  default.vcl: |
{{ tpl .Values.varnishConfigContent . | indent 4 }}
{{- else }}
  default.vcl: |
    vcl 4.0;

    backend default {
      .host = "{{ include "varnish.fullname" . }}-drupal";
      .port = "8080";
    }

{{- end }}
