{{- if .Values.nsiReset.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dotstatsuite.fullname" . }}-reset
  labels:
    {{- include "dotstatsuite.labels" . | nindent 4 }}-reset
spec:
  type: {{ .Values.nsiReset.service.type }}
  ports:
    - port: {{ .Values.nsiReset.service.port }}
      targetPort: http
      protocol: TCP
      name: http-reset
  selector:
    {{- include "dotstatsuite.selectorLabels" . | nindent 4 }}-reset
{{- end -}}
