{{- if .Values.nsiStaging.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dotstatsuite.fullname" . }}-staging
  labels:
    {{- include "dotstatsuite.labels" . | nindent 4 }}-staging
spec:
  type: {{ .Values.nsiStaging.service.type }}
  ports:
    - port: {{ .Values.nsiStaging.service.port }}
      targetPort: http
      protocol: TCP
      name: http-staging
  selector:
    {{- include "dotstatsuite.selectorLabels" . | nindent 4 }}-staging
{{- end -}}
