{{- if .Values.nsiStable.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dotstatsuite.fullname" . }}-stable
  labels:
    {{- include "dotstatsuite.labels" . | nindent 4 }}-stable
spec:
  type: {{ .Values.nsiStable.service.type }}
  ports:
    - port: {{ .Values.nsiStable.service.port }}
      targetPort: http
      protocol: TCP
      name: http-stable
  selector:
    {{- include "dotstatsuite.selectorLabels" . | nindent 4 }}-stable
{{- end -}}
