{{- if .Values.azure.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mlflow.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "mlflow.name" . }}
    helm.sh/chart: {{ include "mlflow.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  azurestorageaccountartifact: {{ .Values.azure.storageaccountartifact | b64enc | quote }}
  azurestorageaccountkey: {{ .Values.azure.storageaccountkey | b64enc | quote }}
{{- end }}
