# Default values for argocd-operator.

operator:
  clusterDomain: ""
  nsToWatch: "argocd-operator-system,argocd-system"
  image:
    repository: statcan/argocd-operator
    tag: v0.0.16
    pullPolicy: IfNotPresent
  imagePullSecrets: []
  podAnnotations: {}
  podLabels: {}
  replicaCount: 1
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    fsGroup: 1000
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
      ephemeral-storage: 500Mi

# ## ArgoCD Projects Definition
# projects:
#   # Project name
#   - name: argprojo01
#     namespace: "argocd-operator-system"
#     podAnnotations: {}
#     podLabels: {}
#     spec:
#       oidcConfig: |
#         name: myoidc
#         issuer: OIDC_FQDN
#         clientID: id
#         clientSecret: secret
#         requestedIDTokenClaims:
#           groups:
#             essential: true
#         requestedScopes: ["openid", "profile", "email"]
#       rbac:
#         defaultPolicy: 'role:readonly'
#         policy: |
#           g, system:cluster-admins, role:admin
#         scopes: '[groups]'
#       server:
#         autoscale:
#           enabled: true
#         host: ARGOCD_FQDN
#         insecure: false

#   # Project name
#   - name: argprojo02
#     namespace: argocd-system
#     podAnnotations: {}
#     podLabels: {}
#     spec:
#       oidcConfig: |
#         name: myoidc
#         issuer: OIDC_FQDN
#         clientID: id
#         clientSecret: secret
#         requestedIDTokenClaims:
#           groups:
#             essential: true
#         requestedScopes: ["openid", "profile", "email"]
#       rbac:
#         defaultPolicy: 'role:readonly'
#         policy: |
#           g, system:cluster-admins, role:admin
#         scopes: '[groups]'
#       server:
#         autoscale:
#           enabled: true
#         host: ARGOCD_FQDN
#         insecure: false
