on: push
name: Publish Helm Chart
jobs:
  publishHelmChart:
    name: Helm gh-pages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Helm gh-pages
      uses: sylus/gh-actions/helm-gh-pages@master
      with:
        args: "stable/* https://statcan.github.io/charts"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
